#!/usr/bin/env python3
"""Generate shim/SDL_keys_gen.h from the SDL_SCANCODE_*/SDLK_* names the emulator uses."""
import re, sys, pathlib
src = pathlib.Path(sys.argv[1]); out = pathlib.Path(sys.argv[2])
text = "".join(p.read_text(errors="ignore") for p in list(src.glob("src/*.cpp")) + list(src.glob("src/*.h")))
sc = set(m for m in re.findall(r"\bSDL_SCANCODE_([A-Z0-9_]+)\b", text) if not m.endswith("_"))
kk = set(re.findall(r"\bSDLK_([A-Za-z0-9_]+)\b", text))
# names that are project-defined (not SDL): skip, they come from the sources themselves
proj = {"CIRC","DEGREE","ESZETT","INV_QUESTION","cCEDIL","nTILDE","uGRAVE"}
known = {"UNKNOWN":0,"RETURN":40,"ESCAPE":41,"BACKSPACE":42,"TAB":43,"SPACE":44,"MINUS":45,"EQUALS":46,
 "LEFTBRACKET":47,"RIGHTBRACKET":48,"BACKSLASH":49,"NONUSHASH":50,"SEMICOLON":51,"APOSTROPHE":52,"GRAVE":53,
 "COMMA":54,"PERIOD":55,"SLASH":56,"CAPSLOCK":57,"PRINTSCREEN":70,"SCROLLLOCK":71,"PAUSE":72,"INSERT":73,
 "HOME":74,"PAGEUP":75,"DELETE":76,"END":77,"PAGEDOWN":78,"RIGHT":79,"LEFT":80,"DOWN":81,"UP":82,
 "NUMLOCKCLEAR":83,"KP_DIVIDE":84,"KP_MULTIPLY":85,"KP_MINUS":86,"KP_PLUS":87,"KP_ENTER":88,"KP_0":98,
 "KP_PERIOD":99,"NONUSBACKSLASH":100,"APPLICATION":101,"POWER":102,"KP_EQUALS":103,
 "LCTRL":224,"LSHIFT":225,"LALT":226,"LGUI":227,"RCTRL":228,"RSHIFT":229,"RALT":230,"RGUI":231}
for i,c in enumerate("ABCDEFGHIJKLMNOPQRSTUVWXYZ"): known[c]=4+i
for i in range(1,10): known[str(i)]=29+i
known["0"]=39
for i in range(1,13): known["F%d"%i]=57+i
for i in range(13,25): known["F%d"%i]=91+i
for i in range(1,10): known["KP_%d"%i]=88+i
# SDLK names that need a scancode entry even if the sources only use the keycode
sdlk_scan = {k for k in kk if k not in proj}
ascii_map = {"AMPERSAND":"'&'","ASTERISK":"'*'","AT":"'@'","BACKQUOTE":"'`'","BACKSLASH":"'\\\\'","CARET":"'^'",
 "COLON":"':'","COMMA":"','","DOLLAR":"'$'","EQUALS":"'='","EXCLAIM":"'!'","GREATER":"'>'","HASH":"'#'",
 "LEFTBRACKET":"'['","LEFTPAREN":"'('","LESS":"'<'","MINUS":"'-'","PERCENT":"'%'","PERIOD":"'.'","PLUS":"'+'",
 "QUESTION":"'?'","QUOTE":"'\\''","QUOTEDBL":"'\"'","RIGHTBRACKET":"']'","RIGHTPAREN":"')'","SEMICOLON":"';'",
 "SLASH":"'/'","SPACE":"' '","UNDERSCORE":"'_'","RETURN":"'\\r'","ESCAPE":"27","BACKSPACE":"8","TAB":"9","DELETE":"127"}
for k in sdlk_scan:
    u = k.upper()
    if k not in ascii_map and not (len(k)==1 and k.isalnum()):
        sc.add(u)
sc |= {"APP1","APP2"} if ("APP1" in kk) else set()
used = set(known.get(n) for n in sc if n in known)
nxt = 116
assign = {}
for n in sorted(sc):
    if n in known: assign[n]=known[n]; continue
    while nxt in used or 224 <= nxt <= 231: nxt += 1
    assign[n]=nxt; used.add(nxt)
assert max(assign.values()) < 512
L = ["// GENERATED by tools/gen_keys.py - do not edit","#pragma once","typedef enum {"]
for n,v in sorted(assign.items(), key=lambda x:x[1]): L.append("  SDL_SCANCODE_%s = %d,"%(n,v))
L += ["  SDL_NUM_SCANCODES = 512","} SDL_Scancode;","","#define SDLK_SCANCODE_MASK (1<<30)",
      "#define SDL_SCANCODE_TO_KEYCODE(X) ((X) | SDLK_SCANCODE_MASK)","typedef int SDL_Keycode;","enum : int {"]
for k in sorted(kk):
    if k in proj: continue
    u=k.upper()
    if k in ascii_map: val=ascii_map[k]
    elif len(k)==1 and k.isalnum(): val="'%s'"%k
    else: val="SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_%s)"%u
    L.append("  SDLK_%s = %s,"%(k,val))
L.append("};")
out.write_text("\n".join(L)+"\n")
print("scancodes:",len(assign),"keycodes:",len(kk)-len(proj&kk))
